# config/services.yaml

parameters:
  gemini_api_key: '%env(GEMINI_API_KEY)%'
  gemini_model: '%env(GEMINI_MODEL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'